config/routes.rb
Rails.application.routes.draw do
  resources :articles
  root 'page#home'
  get 'page/about', to: 'page#about'
  get 'signup', to: 'users#new'
  resources :users, except:[:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 belongs_to :user
 validates :title, presence: true, length: {minimum: 3, maximum: 50}
 validates :description, presence: true, length: {minimum: 10, maximum: 500}

end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
	before_save {self.email = email.downcase}
	validates :username, 
			presence: true, 
			uniqueness: {case_sensitive: false}, 
			length: {minimum: 3}
	VALID_EMAIL_REGEX = /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, 
			presence: true, 
			length: {maximum: 105},
			format: {with: VALID_EMAIL_REGEX}
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :show, :update, :destroy]
	def index
		@articles = Article.all
	end
	def edit
	end
	def show
	end
	def new
		@article = Article.new
	end
	def update
		if @article.update(article_params)
			flash[:danger] = "berhasil update!!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end
	def create
	
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
		flash[:success] = "Artikel berhasil dibuat!!"
		redirect_to article_path(@article)
		else
			render 'new'
		end
	end
	def destroy
		@article.destroy
		flash[:danger] = "Berhasil hapus!!"
		redirect_to articles_path

	end

	private
	def set_article
	@article = Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title, :description)
	end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

	def home
	end

	def about
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to Alphablog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
		flash[:success] = "update success"
		redirect_to articles_path
		else
			render 'edit'
		end
	end
	def show
		@user = User.find(params[:id])
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id= Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt:user.username, class: "rounded-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
<div class="row">
	<div class="col-sm-10 offset-sm-2">
		<div class="card">
			<div class="card-header article-title">
				<%= link_to article.title, article_path(article)%>
			</div>
			<div class="card-body">
				<%= truncate(article.description, length: 100)%>
				<div class="article-meta-details">
					<small>Created by: <%= article.user.username if article.user%>,
						<%= time_ago_in_words(article.created_at)%> ago, last updated: <%= time_ago_in_words(article.updated_at)%>
						ago
						
					</small>
				</div>
			</div>
			<div class="card-footer article-body">
				<%= link_to 'Edit this article', edit_article_path(article), class: 'btn btn-sm btn-primary '%>
				<%= link_to 'Delete this article', article_path(article), method: :delete, data: {confirm: 'Anda yakin?'}, class: 'btn btn-sm btn-danger'%>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article%>

<div class="row">
	<div class="col col-sm-12">
		<%= form_for @article do |f| %>
		
		<div class="form-group row">
				<div class="col-sm col-form-label">
					<%= f.label :title%>
				</div>
				<div class="col-sm-10">
					<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true%>
				</div>
		</div>
		
		<div class="form-group row">
			<div class="col-sm col-form-label">
				
				<%= f.label :text_area%>

			</div>
			<div class="col-sm-10">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Decription Article"%>
			</div>

		</div>
	
		<div class="form-group row">
			<div class="offset-md-2 col-sm-10">
				<%= f.submit class: "btn btn-primary btn-lg"%>
			</div>
		</div>
			
		<% end %>

		<div class="col-sm-4 offset-md-4 ">
			[<%= link_to 'Cancel request and return to article listing', articles_path %>]
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit exiting article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
	<h1 align="center">Listing All Articles</h1>	

<%= render 'article', obj: @articles%>

app/views/articles/new.html.erb
<h1 align="center">Create a new article</h1>

<%= render 'form'%>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="card col-offset-2">
	<h4 class="center description"><strong>Description:</strong></h4>
	<hr>
	<%= simple_format(@article.description)%>
	<div class="article_actions">
		<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-sm btn-primary"%>
		<%= link_to "Delete this article", article_path(@article), method: :delete, data: {confirm: "Are you sure you want to delete the article?"}, class: "btn btn-sm btn-danger"%>
		<%= link_to "View all articles", articles_path, class: "btn btn-sm btn-success"%>

		
	</div>
	
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="#">The Complete Ruby on Rails</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to 'About', page_about_path%></li>
			</ul>
		</nav>
		
	</footer>
</div>

app/views/layouts/_messages.html.erb
<br />
<div class="row">
	<div class="col-md-10 offset-md-1">
	<% flash.each do |name, msg|%>

	<div class="alert alert-<%="#{name}"%>">
		<a href="#" class="close" data-dismis="alert">&#215;</a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
	</div>

	<% end %>
		
	</div>
</div>
	

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg nav-black">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
         <%= link_to 'Articles', articles_path, class: 'nav-link'%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'New Article', new_article_path, class: 'dropdown-item'%>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/navigation'%>
   <%= render 'layouts/messages'%>
   <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  <%= render 'layouts/footer'%>

  </div>
  </body>
</html>

app/views/page/about.html.erb
<h1>Hello, This is about page</h1>

<%= link_to 'Home', root_path%>

app/views/page/home.html.erb
<div class="center jumbotron">
	<h1>ALPHA BLOG</h1>
	<%= link_to 'Sign now up', '#', class: 'btn btn-primary btn-lg btn-xlarge'%>
	
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	
	<div class="alert alert-danger" role="alert">
	<b>
		<%=pluralize(obj.errors.count, "errors") %>
		prohibited this article being saved:
	</b>	
	<ul>
		<% obj.errors.full_messages.each do |msg|%>

		<li><%= msg %></li>
		<%end%>
	</ul>
	</div>

<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user%>


<div class="row">
	<div class="col col-sm-12">
		<%= form_for @user do |f| %>
		
		<div class="form-group row">
				<div class="col-sm col-form-label">
					<%= f.label :username%>
				</div>
				<div class="col-sm-10">
					<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true%>
				</div>
		</div>
		
		<div class="form-group row">
			<div class="col-sm col-form-label">
				
				<%= f.label :email%>

			</div>
			<div class="col-sm-10">
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email"%>
			</div>

		</div>

		<div class="form-group row">
			<div class="col-sm col-form-label">
				
				<%= f.label :password%>

			</div>
			<div class="col-sm-10">
				<%= f.password_field :password, class: "form-control", placeholder: "Enter password"%>
			</div>

		</div>
	
		<div class="form-group row">
			<div class="offset-md-2 col-sm-10">
				<%= f.submit(@user.updated_at? ? "Update Account" : "Signup", class: "btn btn-primary btn-lg")%>
			</div>
		</div>
			
		<% end %>

		<div class="col-sm-4 offset-md-4 ">
			[<%= link_to 'Cancel request and return to article listing', articles_path %>]
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Edit Users</h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 align="center"> All Alpa Bloggers</h1>
<div align="center">
  <% @users.each do |user|%>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user)%></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user)%>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<center>
	<h1>Signup a new users</h1>
</center>

<%= render "form"%>

app/views/users/show.html.erb
<h1 align="center">Welcome back <%= @user.username%>'s to page</h1>
<div class="row">
	<div class="col col-md offset-md-5">
		<%= gravatar_for @user, size: 150%>
	</div>
</div>
<h4 align="center">Articles <%= @user.username%></h4>

<%= render 'articles/article', obj: @user.articles%>